version: "3"
services:
  app:
    image: app
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
    ports:
      - "5000:80"
  app1:
    image: app1
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
    ports:
      - "5001:80"
  app2:
    image: app2
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
    ports:
      - "5002:80"
  app3:
    image: app3
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
    ports:
      - "5003:80"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
networks:
  frontend: