version: "3"
services:
  app:
    depends_on:
      - app1
      - app2
      - app3
    image: rafaellucio/app:0.0.1
    ports:
      - "9000:80"
    networks:
      - frontend
  app1:
    image: rafaellucio/app1:0.0.1
    ports:
      - "9001:80"
    networks:
      - frontend
  app2:
    image: rafaellucio/app2:0.0.1
    ports:
      - "9002:80"
    networks:
      - frontend
  app3:
    image: rafaellucio/app3:0.0.1
    ports:
      - "9003:80"
    networks:
      - frontend
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
networks:
  frontend:
